Mats and Evelina's labyrinth
Technigo/project-labyrinth pull request #19
Opened 2020-12-05 10:48 UTC by evelinabe

Link to my deployed project: https://labyrinth-2020.netlify.app/

Our reflections on how this week's project turned out: We had some issues with fetching the games data from the API and in the end we noticed that the problem was due to a naming error in the function that was executing the fetch.

2020-12-16 08:53 UTC, emma-tech reviewed
Your project looks really good Mats and Evelina! The code is clean, well structured and easy to read. We're really impressed with how you've structured your styling as well, will be some inspiration for us to take with us to future projects 👍

We have left some comments on out-commented code and extra whitespace that we found in the project, so maybe have a look at that :) Otherwise you've met all the requirements and we thinks you project is approved 🌟👏

//Emma, Petra, Sara

2020-12-16 08:53 UTC, emma-tech commented on code/src/components/Loader.js
> +	      options={defaultOptions}
To much indent here! :)

2020-12-16 08:53 UTC, emma-tech commented on code/src/components/Loader.js
> +        preserveAspectRatio: "xMidYMid slice"
To much indent here! :)

2020-12-16 08:53 UTC, emma-tech commented on code/src/reducers/game.js
> +        // setHistory: (state, action) => {
Don't forget to remove out-commented code before last commit! :)

2020-12-16 08:53 UTC, emma-tech commented on code/src/reducers/reusable.js
> + //               localStorage.setItem("game", JSON.stringify(json[0]));
Some out-commented code here :)

2020-12-16 08:53 UTC, emma-tech commented on code/src/reducers/reusable.js
> +    console.log("hellog")
Don't forget to remove console.log()'s  before last commit :)

2020-12-16 08:53 UTC, emma-tech commented on code/src/components/GameContinue.js
> +
Some extra whitespace here that can be removed :)

2020-12-16 08:53 UTC, emma-tech commented on code/src/components/GameStart.js
> +export const GameStart = () => {
Your code is so well structured and clean, really easy to read 🌟👏

2020-12-16 08:53 UTC, emma-tech commented on code/src/components/GameStart.js
> +            <GameButton onClick={handleSubmit} width={100} disabled={!userNameInput}>Let's go!</GameButton>
Really good that you disabled the button if the user hasn't typed in a user name (will change that in our own application as well! 👍)

2020-12-16 08:53 UTC, emma-tech commented on code/src/components/Loader.js
> +import animationData from '../lib/lotties/40235-si-fi-circle.json';
Really cool loader 😍

2020-12-16 08:53 UTC, emma-tech commented on code/src/lib/Button.js
> +import styled from 'styled-components';
Really good that you're so consistent with your styling, that you use styled components and that you have structured them using these lib/ folders 🌟

2020-12-16 08:53 UTC, emma-tech commented on code/src/reducers/game.js
> +// const initialContent = localStorage.getItem('game')
Don't forget to remove out-commented code :)

2020-12-16 08:54 UTC, emma-tech commented
You've reached the requrements for this week and we think the project is approved 👍

2020-12-16 08:54 UTC, emma-tech approved these changes

2020-12-30 15:22 UTC, puj requested changes
Nice job.  Good result and clean, logical code along the way.  Changes requested before approval:
- Remove commented code
- Remove `console.log`s

2020-12-30 15:22 UTC, puj commented on code/src/components/GameContainer.js
> +            {gameStart ? <GameContinue /> : <></>}
`{gameStart  && <GameContinue /> }` works the same as this

2021-02-16 15:10 UTC, evelinabe commented
> Nice job. Good result and clean, logical code along the way. Changes requested before approval:
> 
> * Remove commented code
> * Remove `console.log`s

Fixed!

2021-03-09 12:40 UTC, closed without merging