Mine and Jonna Ru's maze adventure
Technigo/project-labyrinth pull request #21
Opened 2020-12-05 18:46 UTC by ssundblom

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2020-12-05 18:46 UTC, ssundblom commented
https://adventure-maze.netlify.app/

2020-12-07 12:50 UTC, johannarexin requested changes
Great job, your game looks great!

We don't see that you have used media queries in your code. We think it looks great in mobile, ok on tablet but in desktop the text is jumping around since it's centered but has no width. Maybe a good idea to add it to make the site responsive (that's why we have chosen "Request changes").

Nice that you have a restart button :) And also that you have the coordinates. 
We find you code clean and easy to understand, nice job! It was fun to learn about sweetalert and that you used one button with different text alternatives :) 

/Johanna & Annika

2020-12-07 12:50 UTC, johannarexin commented on code/src/App.js
> +      {!isLoading && <GameState />}
Another way to do this is to write like this:

```
{!isLoading && 
<>
<StartGame />
<GameState />
</>
}
```

2020-12-07 12:50 UTC, johannarexin commented on code/src/components/Action.js
> +import styled from 'styled-components'
You should write it in this order:

import React, { useState } from 'react'
import { useSelector, useDispatch } from 'react-redux'
import styled from 'styled-components'

import { executeAction } from '../reducers/game'

2020-12-07 12:50 UTC, johannarexin commented on code/src/components/Action.js
> +    </div>
From an UX and accessibility perspective we would prefer the button to have the {direction}. So the buttons say either "Go west" or "Go north" for example. We don't think it's a good idea to have two buttons with the same text.

2020-12-07 12:50 UTC, johannarexin commented on code/src/components/GameState.js
> +import { Action } from "./Action"
It should be written like this:

import React from 'react'
import { useSelector } from 'react-redux'

import { Action } from "./Action"

2020-12-07 12:50 UTC, johannarexin commented on code/src/components/GameState.js
> +      {actions && actions.map(action => {
Is first "actions" needed?

2020-12-07 12:50 UTC, johannarexin commented on code/src/components/Loading.js
> +    <>{isLoading && <div>!! Loading !!</div>}</>
We think that "isLoading" can be removed as you have conditionals for this in App.js.

2020-12-07 12:50 UTC, johannarexin commented on code/src/components/StartGame.js
> +import styled from 'styled-components'
Should be written like this:

import React from 'react'
import { useDispatch, useSelector } from 'react-redux'
import swal from "sweetalert";
import styled from 'styled-components'

import { startNewGame } from 'reducers/game';

2020-12-07 12:50 UTC, johannarexin commented on code/src/components/StartGame.js
> +  };
Nice using swal! We have never used it before but got inspired to do so! Clean and nice code.

2020-12-07 12:50 UTC, johannarexin commented on code/src/components/StartGame.js
> +      <StartButton onClick={handleOnClick}>{username === '' ? 'Play' : 'Restart'}</StartButton>
Very smart using the same button but with different text alternatives.

2020-12-07 12:50 UTC, johannarexin commented on code/src/index.css
> +  border: 1px solid #4CFF42;
Why are you styling swal with regular CSS? Can't you use styled components for this?

2020-12-07 12:50 UTC, johannarexin commented on code/src/reducers/game.js
> +      return newState
Why is return needed here?

2020-12-07 12:50 UTC, johannarexin commented on code/src/reducers/game.js
> +      return newState
Why is return needed here?

2020-12-07 12:50 UTC, johannarexin commented on code/src/reducers/reusable.js
> +}
Can this be merged to executeAction?

2021-01-04 08:46 UTC, puj approved these changes
Clearly structured!  I like the consistency in both the code and the design.  
It's evident that you considered your solutions very carefully and iterated a few times.  

Very nice project!  Well done.

2021-01-04 08:46 UTC, puj commented on code/src/components/Action.js
> +      buttonText={`${type} ${direction}`}
Nice thinking! 💯

2021-01-04 08:46 UTC, puj commented on code/src/components/GameState.js
> +              return <Action key={action.description} {...action} />;
Clean

2021-01-04 08:46 UTC, puj commented on code/src/components/History.js
> +        ))}
`.slice(-9)` is understandable to limit the height of the column with the action history; however, from purely a code perspective the -9 might seem a bit arbitrary.   

`.slice(NUM_HISTORY_ITEMS_VISIBLE)` could be more clear.  Also, some visually indicator to the user that they are not viewing their entire history 👍

2021-01-04 08:46 UTC, puj commented on code/src/components/Loading.js
> +`;
Love this.

2021-01-04 08:46 UTC, puj commented on code/src/components/StartGame.js
> +    </StyledButton>
Prefer a constant here.  Ideally something like
```javascript
const isNewPlayer = isEmpty(username);
...

   {isNewPlayer ? "Play" : "Restart"}
```

2021-03-09 12:40 UTC, closed without merging