Labyrinth Anna Hasselström & Nathalie Nordström
Technigo/project-labyrinth pull request #29
Opened 2020-12-08 09:54 UTC by nathalienordstrom

https://labyrint-game.netlify.app

2020-12-08 09:54 UTC, nathalienordstrom commented
a

2020-12-09 14:10 UTC, Snabbina requested changes
🤩 Hey, Anna and Nathalie!

What a mysterious game you've made!

You have worked well with the layout in the various media queries, and nice elements in the styling where there is a consistent theme in both color and shapes.

The main features are included which allows the game to go through from start to finish. and also the opportunity to go back a step or to start over is a practical feature.
Great job with the styled components! The naming of functions and variables is clear and consistent through out the code.

Also very impressed with your solution with the conditional rendering for the different components. 

We have a changes requested before approval though:
- Not consistent with ;, semikolon. For example in App.js and PlayingGame.js you use ; but in GameOver and loading you are not using them anymore. Change to one approach.
- indentation is missing in some places. 

Please see our comments, questions and extra appreciation for your code!
🎉

Best of the best from Sabina and Ellen!

2020-12-13 15:13 UTC, nathalienordstrom commented
All done thank you Sabina and Ellen

2021-01-04 15:30 UTC, HIPPIEKICK commented on code/src/components/StartingGame.js
> +          <Button type="button" onClick={() => dispatch(firstFetch(username))}>Play Game</Button>
I agree, the start button should be hidden or disabled if it's not possible to start the game 👍

2021-01-04 15:31 UTC, HIPPIEKICK commented on code/src/components/GameOver.js
> +    )
Yes, this should be indented. And no need for the fragment

2021-01-04 15:32 UTC, HIPPIEKICK commented on code/src/components/Loading.js
> +    const isLoading = useSelector((state) => state.ui.isLoading)
Great name of a boolean!

2021-01-04 15:34 UTC, HIPPIEKICK commented on code/src/components/PlayingGame.js
> +    }
Goes for this whole file

2021-01-04 15:37 UTC, HIPPIEKICK commented on code/src/reducers/currentstate.js
> +    historyGoBack: state => {
Maybe `goBack` would be a fitting name?

2021-01-04 15:38 UTC, HIPPIEKICK commented on code/src/reducers/currentstate.js
> +import { ui } from './ui'
;

2021-01-04 15:39 UTC, HIPPIEKICK commented on code/src/reducers/ui.js
> +import { createSlice } from '@reduxjs/toolkit'
Semicolons missing in this file ;)

2021-01-04 15:43 UTC, HIPPIEKICK commented
Hi Anna and Nathalie! Please check indentation and semicolons in all files. Also, I would like to ask you to think about your starting screen. Right now it's not clear that you have to click Save before Play Game. Once you've saved - you get no indicator of that the save was successful. One suggestion is to only have the Save button visible to start with, and then after the save is done, that section is hidden and the start screen only shows the Play Game button. Alternatively, you could display a message to the user saying that the save was successful and apply some more styling to the disabled Play Game button so the user knows it's not possible to start.

2021-03-09 12:40 UTC, closed without merging