Labryrinth - Sandra and Karan
Technigo/project-labyrinth pull request #4
Opened 2020-12-04 09:33 UTC by karanmann

Link to my deployed project: https://labyrinth-react-redux.netlify.app

This weeks project was made by Sandra(https://github.com/sandra-shumanteva-kaevska) and me. Our reflections on how this week's project turned out: It was a tough project and we really had to push our limits on understanding how the dispatches and actions effected in Redux Toolkit.

2020-12-08 15:31 UTC, mhammarback requested changes
The code was extra hard to read because of the indentation, we are requesting changes as reminder to review your code before turning it in :) 

Requested changes: 
- remove commented out code 
-  review indentation ( all pages ) 
- remove extra line spaces
- It's great that you used material ui, but maybe add some extra margin for the direction buttons. 
- Your page response to different devices, however, it is not styled for different devices. For exempel, any extra padding and margin on top should be reviewed for display on mobil. 

![File](https://user-images.githubusercontent.com/63230455/101502808-af4bcc00-3971-11eb-8599-7d8be9cb82f6.jpg)

We know you had some trouble getting started this week but you where able to successfully
produce the labyrinth app, including the blue level and even some of the red. Great work Karan and Sandra!

2020-12-08 15:31 UTC, mhammarback commented on code/src/index.css
> +
delete commented code

2020-12-08 15:31 UTC, mhammarback commented on code/src/reducers/games.js
> +		history: state => {
yay with history!

2020-12-08 15:31 UTC, mhammarback commented on code/src/reducers/games.js
> +export const thunk = (userName) => {
It would be nice to have the thunks/fetches in its own file

2020-12-08 21:13 UTC, karanmann commented
Thank you Moa and Peggy for the review. 
Yes this week was a bit messed up with me being distracted. 
We have gone ahead and made the requested changes now :)

2020-12-28 10:29 UTC, puj commented
Great job!  
I love that you used Material UI, adds so much value.  I think Moa's requested change for the buttons still needs to be adjusted
![image](https://user-images.githubusercontent.com/807352/103207923-c857f500-48ff-11eb-8de5-a863e939fcca.png)

My change request is:
- If you are going to show the loading icon while you are displayed the actions for the current room, disable the buttons (you can still click them while the loader is visible)
- Maybe move the loader below the description/actions so the text doesn't "jump" when the loader shows/hides

2020-12-28 10:30 UTC, puj requested changes
See my comment with 2 changes requested

2021-01-05 09:13 UTC, karanmann commented
> Great job!
> I love that you used Material UI, adds so much value. I think Moa's requested change for the buttons still needs to be adjusted
> ![image](https://user-images.githubusercontent.com/807352/103207923-c857f500-48ff-11eb-8de5-a863e939fcca.png)
> 
> My change request is:
> 
> * If you are going to show the loading icon while you are displayed the actions for the current room, disable the buttons (you can still click them while the loader is visible)
> * Maybe move the loader below the description/actions so the text doesn't "jump" when the loader shows/hides


Hi Van,

I have done the changes as requested. About the button. We had decided to go with button grouping and use the template accordingly. I had conveyed the same to Moa and Peggy too. If you still think we should change it we could do it.

best regards
Sandra & Karan

2021-02-03 09:46 UTC, puj commented
The changes turned out really good! Great job! Approving!  Nice choice with the disable style!

2021-02-03 09:46 UTC, puj approved these changes

2021-03-09 12:40 UTC, closed without merging