Week 16, Project Labyrinth - Anna Lenksjö & Isabella Markskog
Technigo/project-labyrinth pull request #40
Opened 2021-04-30 11:43 UTC by IsabellaM5

**Link to our deployed project**
https://goofy-dijkstra-c1398c.netlify.app/ 

**Our reflections on how this week's project turned out**
The first two days were a bit hard to get into and grasp the concept of using thunks in API calls. Also structuring the POST request body to get the desired API response was tricky. After figuring out how to do this, we felt the rest of the days went relatively smooth. We found a picture that we really liked which we adapted the rest of the styling to and we're so happy with the end result! 🤩 All in all, a fun project!

**Things we'd like to have clarified or explained in more detail**
We would've liked a more detailed description of the concept of this labyrinth game to get a more feel for it. It took some time to get into the thinking of how to structure it.

Other than that, perhaps more explanation about localStorage and the functionality for it.

/Anna & Isabella 🐯🐯

2021-05-05 17:22 UTC, ElleFrankenberg approved these changes
Great work!!! You definitely fullfilled the blue requirements and more💥 Clean code and really good naming.  Nice design on both tablet and desktop! 
The only comment that I have is when I viewed this on my iPhone the input field was a bit to long to fit the screen.  Besides this it is all 🙌

2021-05-07 18:59 UTC, KarolCislowski requested changes
After I give my character name I have instantly seen this page: ![image](https://user-images.githubusercontent.com/50926159/117496004-b1dd3c80-af76-11eb-9181-2e54ccbff0dc.png)
Refreshing the page doesn't change anything. If you are using local storage to persist your data please remember to give your user possibility to clean it (Restart button for example)

2021-05-24 13:53 UTC, IsabellaM5 commented
Hi @KarolCislowski 

Please see our above message. 

/Anna & Isabella

2021-05-31 12:28 UTC, KarolCislowski approved these changes
Really nice game 🎮

2021-05-31 12:28 UTC, KarolCislowski commented on code/src/App.js
> +`
nice global tyle 👍🏻

2021-05-31 12:28 UTC, KarolCislowski commented on code/src/components/Content.js
> +  background-color: rgb(82,88,13, 0.7);
you should specify `rgba` when you are using the alpha canal.

2021-05-31 12:28 UTC, KarolCislowski commented on code/src/components/Content.js
> +            </CustomButton>
Great idea 👍🏻

2021-05-31 12:28 UTC, KarolCislowski commented on code/src/components/GameCard.js
> +  )
you do not need <></> here 🤓

2021-05-31 12:28 UTC, KarolCislowski commented on code/src/components/GameScreen.js
> +    0px 1px 1px 0px rgb(0 0 0 / 14%), 0px 1px 3px 0px rgb(0 0 0 / 12%);
Nice 👍🏻

2021-05-31 12:28 UTC, KarolCislowski commented on code/src/components/StartScreen.js
> +    </>
another misplaced use of the <></> 🤓

2021-05-31 12:28 UTC, KarolCislowski commented on code/src/reducers/labyrinth.js
> +    loading: false
Nice initial state 👍🏻

2021-05-31 12:28 UTC, KarolCislowski commented on code/src/reducers/labyrinth.js
> +}
💯

2021-05-31 12:30 UTC, KarolCislowski commented
Hello, it's your project. Do you remember me? I may be imperfect, but I believe you can still change that before you sit down to your final masterpiece!
![image](https://user-images.githubusercontent.com/50926159/120141019-f9ed2900-c1db-11eb-95df-db20da4f1088.png)

2021-11-01 15:00 UTC, closed without merging