Project Labyrinth by Pauline Andersson & Ann-Sofi Jönsson
Technigo/project-labyrinth pull request #43
Opened 2021-04-30 13:47 UTC by Ann-Sofi

2021-05-03 16:07 UTC, darcywinterhill approved these changes
Overall a fun, clean project that's easy to navigate through! 🎉👌🏼

2021-05-08 08:25 UTC, KarolCislowski requested changes
After I click the start button I saw this page: 
![image](https://user-images.githubusercontent.com/50926159/117532390-9e1dee80-afe7-11eb-9867-9465d624ed3d.png)
I'm really hungry for adventure so please fix it and let me play ⚔️

2021-05-09 11:18 UTC, KarolCislowski approved these changes
After a deep analysis of your code, I found out that the issue I pointed before was closed by API, not by error inside your code. I sent a memo about it to teachers and I need to sorry for any inconvenience done because of it 😢

2021-05-09 11:18 UTC, KarolCislowski commented on code/src/App.js
> +import labyrinth from './reducers/labyrinth'
Check your Prettier config to make it add/remove all semicolons for you 😸

2021-05-09 11:18 UTC, KarolCislowski commented on code/src/components/GameScreen.js
> +      default: return <i className="nes-icon is-medium star"></i>
Nice :)

2021-05-09 11:18 UTC, KarolCislowski commented on code/src/components/GameScreen.js
> +          </button></div>)
If you mapping something it is a good practice to create a separate Component and return it here. It is easier to read and debug 🤓

2021-05-09 11:18 UTC, KarolCislowski commented on code/src/components/StartScreen.js
> +        </button>
It is another example of a great opportunity to create a separate component 😸

2021-11-01 15:00 UTC, closed without merging