Labyrinth - Maria Pogosjan & Fethullah Dincer
Technigo/project-labyrinth pull request #54
Opened 2021-05-02 15:40 UTC by MariaPogosjan

Link to my deployed project:
https://meze-game.netlify.app/

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:
We did not manage to find a unique key from the API when we wore mapping. How should we solve it?

2021-05-08 18:16 UTC, klimenko3007 requested changes
Great job, guys! Your code looks very clean and easy to read! No forgotten console.logs anywhere :D  There are couple of issues though when it comes to styling. It does not always scale well on small mobile devices. We added a couple of suggestions on how to fix it.

2021-05-10 10:09 UTC, KarolCislowski approved these changes
Awesome app 😺

2021-05-10 10:09 UTC, KarolCislowski commented on code/src/components/Description.js
> +        ))}
map has an extra parameter- index. 

```jsx
  arr.map((action, index) => (
    <Component key={`key-${index}`}
  )
```

2021-05-10 10:09 UTC, KarolCislowski commented on code/src/components/WelcomePage.js
> +        </button>
It is not nice that you forgot about the form tag. It striped your input from submission on enter, what is the most used sending the form method 😭

2021-05-10 10:09 UTC, KarolCislowski commented on code/src/components/ActionHistory.js
> +            <p className='action-text'>{option}</p>
It would be nice to separate every word with space 🤓

2021-11-01 14:59 UTC, closed without merging